feat(treenode-column): left alignment and only deepest node shown
Neovici/cosmoz-omnitable-treenode-column pull request #102
Opened 2023-11-14 14:24 UTC by CarloBar1

User Story AB#12784 - the new treenode column includes only the deepest node, and visualizes the whole rest of the treenode on hover in a tooltip.

https://github.com/Neovici/cosmoz-omnitable-treenode-column/assets/122988480/9a21deee-36b0-4f0a-a38b-381f9defd6a5

2023-11-14 15:25 UTC, megheaiulian approved these changes

2023-11-14 15:25 UTC, megheaiulian commented on cosmoz-omnitable-treenode-column.js
> +				show-max-nodes=${column.showMaxNodes ? column.showMaxNodes : '1'}
```suggestion
				show-max-nodes=${column.showMaxNodes ?? '1'}
```

2023-11-14 15:25 UTC, megheaiulian commented on cosmoz-omnitable-treenode-column.js
> +				show-max-nodes=${column.showMaxNodes ? column.showMaxNodes : '1'}
```suggestion
				show-max-nodes=${column.showMaxNodes ||  '1'}
```

2023-11-14 20:08 UTC, cristinecula requested changes
This works, but you should instead define the default value of 1 here: https://github.com/Neovici/cosmoz-omnitable-treenode-column/blob/master/cosmoz-omnitable-treenode-column.js#L68C6-L68C6

2023-11-15 08:23 UTC, megheaiulian approved these changes

2023-11-15 10:31 UTC, cristinecula approved these changes
Nice!

2023-11-15 10:32 UTC, merged